scipt ported to IBM machines

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -270,7 +270,7 @@ PACKAGE_VERSION='0.01'
 PACKAGE_STRING='MCT 0.01'
 PACKAGE_BUGREPORT=''
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT F90 F90FLAGS ac_ct_F90 MPIF90 MPILIBS MUPDATE CPP FRULE F90RULE FRULECPP F90RULECPP MACHDEFS LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT F90 F90FLAGS ac_ct_F90 MPIF90 MPILIBS FC MUPDATE FPP FPPFLAGS CPP FRULE F90RULE FRULECPP F90RULECPP MACHDEFS FFLAGS REAL8 LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -739,14 +739,34 @@ ac_env_MPIF90_set=${MPIF90+set}
 ac_env_MPIF90_value=$MPIF90
 ac_cv_env_MPIF90_set=${MPIF90+set}
 ac_cv_env_MPIF90_value=$MPIF90
+ac_env_FC_set=${FC+set}
+ac_env_FC_value=$FC
+ac_cv_env_FC_set=${FC+set}
+ac_cv_env_FC_value=$FC
 ac_env_MUPDATE_set=${MUPDATE+set}
 ac_env_MUPDATE_value=$MUPDATE
 ac_cv_env_MUPDATE_set=${MUPDATE+set}
 ac_cv_env_MUPDATE_value=$MUPDATE
+ac_env_FPP_set=${FPP+set}
+ac_env_FPP_value=$FPP
+ac_cv_env_FPP_set=${FPP+set}
+ac_cv_env_FPP_value=$FPP
+ac_env_FPPFLAGS_set=${FPPFLAGS+set}
+ac_env_FPPFLAGS_value=$FPPFLAGS
+ac_cv_env_FPPFLAGS_set=${FPPFLAGS+set}
+ac_cv_env_FPPFLAGS_value=$FPPFLAGS
 ac_env_MACHDEFS_set=${MACHDEFS+set}
 ac_env_MACHDEFS_value=$MACHDEFS
 ac_cv_env_MACHDEFS_set=${MACHDEFS+set}
 ac_cv_env_MACHDEFS_value=$MACHDEFS
+ac_env_FFLAGS_set=${FFLAGS+set}
+ac_env_FFLAGS_value=$FFLAGS
+ac_cv_env_FFLAGS_set=${FFLAGS+set}
+ac_cv_env_FFLAGS_value=$FFLAGS
+ac_env_REAL8_set=${REAL8+set}
+ac_env_REAL8_value=$REAL8
+ac_cv_env_REAL8_set=${REAL8+set}
+ac_cv_env_REAL8_value=$REAL8
 
 #
 # Report the --help message.
@@ -826,8 +846,13 @@ Some influential environment variables:
   F90         Fortran 90 compiler command
   F90FLAGS    Fortran 90 compiler flags
   MPIF90      MPI Fortran compiler command
+  FC          The Fortran compiler
   MUPDATE     Find and copy F90 modules to a directory
+  FPP         C-preprocessor for Fortran source code
+  FPPFLAGS    C-preprocessing flags for Fortran source code
   MACHDEFS    MCT compiler and OS flags
+  FFLAGS      Fortran compiler flags for all source files
+  REAL8       Fortran compiler flag for setting the size of REAL values
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -1250,8 +1275,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
                               ac_config_files="$ac_config_files mpeu/mpi0/Makefile.conf mpeu/Makefile.conf mct/Makefile.conf"
 
 
-# We want to use cpp for preprocessing.
-# "gcc -E" absolutely sucks in this capacity.
+# Check for the C compiler
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -1905,7 +1929,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 # Check for the Fortran compiler.
-ac_ext=f90
+ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
@@ -1996,8 +2020,97 @@ done
 fi
 
 
+echo "$as_me:$LINENO: checking Fortran compiler source file extension" >&5
+echo $ECHO_N "checking Fortran compiler source file extension... $ECHO_C" >&6
+ac_ext=F90
+cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+
+end program main
+
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  echo "$as_me:$LINENO: result: .F90" >&5
+echo "${ECHO_T}.F90" >&6
+else
+
+ac_ext=f90
+cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+
+end program main
+
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  echo "$as_me:$LINENO: result: .f90" >&5
+echo "${ECHO_T}.f90" >&6
+else
+
+ac_ext=F
+cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+
+end program main
+
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  echo "$as_me:$LINENO: result: .F" >&5
+echo "${ECHO_T}.F" >&6
+else
+
+ac_ext=f
+cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+
+end program main
+
+_ACEOF
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  echo "$as_me:$LINENO: result: .f" >&5
+echo "${ECHO_T}.f" >&6
+else
+
+{ { echo "$as_me:$LINENO: error: Cannot determine source file extension
+See \`config.log' for more details." >&5
+echo "$as_me: error: Cannot determine source file extension
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+
+fi
+
+fi
+
+fi
+
+
 # Provide some information about the compiler.
-echo "$as_me:2000:" \
+echo "$as_me:2113:" \
      "checking for Fortran 90 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -2070,8 +2183,9 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
+
 # Check for MPI libraries.
-ac_ext=f90
+ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
@@ -2311,7 +2425,8 @@ fi
 
 # If MPIF90 exists, check if it is built from F90
 # If MPIF90 exists, set F90=MPIF90
-echo "$as_me:$LINENO: checking how to get the version output from $F90" >&5
+if test "$F90" != "xlf90"; then
+   echo "$as_me:$LINENO: checking how to get the version output from $F90" >&5
 echo $ECHO_N "checking how to get the version output from $F90... $ECHO_C" >&6
 if test "${ac_cv_prog_f90_version+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -2339,8 +2454,8 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (exit $ac_status); }; }; then
   ac_cv_prog_f90_version=
 # Try some options frequently used verbose output
-for ac_version in  -V -version --version -v; do
-  ac_ext=f90
+for ac_version in -V -version --version; do
+  ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
@@ -2358,13 +2473,13 @@ _ACEOF
 # 1 to this macro) to the Fortran 90 compiler in order to get "version" output
 ac_save_F90FLAGS=$F90FLAGS
 F90FLAGS="$F90FLAGS $ac_version"
-(eval echo $as_me:2361: \"$ac_link\") >&5
+(eval echo $as_me:2476: \"$ac_link\") >&5
 ac_f90_version_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f90_version_output" >&5
 F90FLAGS=$ac_save_F90FLAGS
 
 rm -f conftest.*
-ac_ext=f90
+ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
@@ -2373,7 +2488,7 @@ ac_compiler_gnu=$ac_cv_f90_compiler_gnu
   # look for "copyright" constructs in the output
   for ac_arg in $ac_f90_version_output; do
      case $ac_arg in
-        COPYRIGHT | copyright | Copyright | '(c)' | Compiler)
+        COPYRIGHT | copyright | Copyright | '(c)' | '(C)' | Compiler | Version)
           ac_cv_prog_f90_version=$ac_version
           break 2 ;;
      esac
@@ -2395,56 +2510,40 @@ rm -f conftest.$ac_objext conftest.$ac_ext
 fi
 echo "$as_me:$LINENO: result: $ac_cv_prog_f90_version" >&5
 echo "${ECHO_T}$ac_cv_prog_f90_version" >&6
+fi
 f90_version="$ac_f90_version_output"
 
+
 if test "$F90" != "$MPIF90";  then
-
-   F90_old="$F90"
-   F90="$MPIF90"
-   ac_ext=f90
-ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
-ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f90_compiler_gnu
-
-cat >conftest.$ac_ext <<_ACEOF
-
-program main
-
-
-end program main
-
-_ACEOF
-
-# Compile and link our simple test program by passing a flag (argument
-# 1 to this macro) to the Fortran 90 compiler in order to get "version" output
-ac_save_F90FLAGS=$F90FLAGS
-F90FLAGS="$F90FLAGS $ac_cv_prog_f90_version"
-(eval echo $as_me:2422: \"$ac_link\") >&5
-ac_f90_version_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
-echo "$ac_f90_version_output" >&5
-F90FLAGS=$ac_save_F90FLAGS
-
-rm -f conftest.*
-ac_ext=f90
-ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
-ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f90_compiler_gnu
-
-
-   mpif90_version="$ac_f90_version_output"
-
-   if test "$f90_version" != "$mpif90_version"; then
-      { echo "$as_me:$LINENO: WARNING: F90 version does not match MPIF90 version!" >&5
-echo "$as_me: WARNING: F90 version does not match MPIF90 version!" >&2;}
-   fi
-
-   f90_version="$mpif90_version"
-
+   FC=$MPIF90
+else
+   FC=$F90
 fi
+
+#if test "$F90" != "$MPIF90";  then
+#   F90_old="$F90"
+#   F90="$MPIF90"
+#   _AC_PROG_F90_VERSION_OUTPUT([$ac_cv_prog_f90_version])
+#   mpif90_version="$ac_f90_version_output"
+
+#   if test "$f90_version" != "$mpif90_version"; then
+#      AC_MSG_WARN([F90 version does not match MPIF90 version!])
+#   fi
+
+#   f90_version="$mpif90_version"
+#fi
+
+ac_ext=c
+ac_cpp='$CPP $CPPFLAGS'
+ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_c_compiler_gnu
+
 
 # Checks for compiler characteristics.
 
 # Check for endianness
+
 echo "$as_me:$LINENO: checking whether byte ordering is bigendian" >&5
 echo $ECHO_N "checking whether byte ordering is bigendian... $ECHO_C" >&6
 if test "${ac_cv_c_bigendian+set}" = set; then
@@ -2452,17 +2551,25 @@ if test "${ac_cv_c_bigendian+set}" = set; then
 else
   # See if sys/param.h defines the BYTE_ORDER macro.
 cat >conftest.$ac_ext <<_ACEOF
-
-program main
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 #include <sys/types.h>
 #include <sys/param.h>
 
+int
+main ()
+{
 #if !BYTE_ORDER || !BIG_ENDIAN || !LITTLE_ENDIAN
  bogus endian macros
 #endif
 
-end program main
-
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -2478,17 +2585,25 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (exit $ac_status); }; }; then
   # It does; now see whether it defined to BIG_ENDIAN or not.
 cat >conftest.$ac_ext <<_ACEOF
-
-program main
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 #include <sys/types.h>
 #include <sys/param.h>
 
+int
+main ()
+{
 #if BYTE_ORDER != BIG_ENDIAN
  not big endian
 #endif
 
-end program main
-
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -2519,17 +2634,25 @@ if test "$cross_compiling" = yes; then
   # try to guess the endianness by grepping values into an object file
   ac_cv_c_bigendian=unknown
   cat >conftest.$ac_ext <<_ACEOF
-
-program main
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 short ascii_mm[] = { 0x4249, 0x4765, 0x6E44, 0x6961, 0x6E53, 0x7953, 0 };
 short ascii_ii[] = { 0x694C, 0x5454, 0x656C, 0x6E45, 0x6944, 0x6E61, 0 };
 void _ascii () { char *s = (char *) ascii_mm; s = (char *) ascii_ii; }
 short ebcdic_ii[] = { 0x89D3, 0xE3E3, 0x8593, 0x95C5, 0x89C4, 0x9581, 0 };
 short ebcdic_mm[] = { 0xC2C9, 0xC785, 0x95C4, 0x8981, 0x95E2, 0xA8E2, 0 };
 void _ebcdic () { char *s = (char *) ebcdic_mm; s = (char *) ebcdic_ii; }
+int
+main ()
+{
  _ascii (); _ebcdic ();
-end program main
-
+  ;
+  return 0;
+}
 _ACEOF
 rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
@@ -2562,6 +2685,12 @@ fi
 rm -f conftest.$ac_objext conftest.$ac_ext
 else
   cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
 int
 main ()
 {
@@ -2630,7 +2759,7 @@ if test "${ac_cv_f90_mod_uppercase+set}" = set; then
 else
   # try to guess the endianness by grepping values into an object file
 ac_cv_f90_mod_uppercase=unknown
-ac_ext=f90
+ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
@@ -2707,15 +2836,24 @@ fi
 # Set the Makefiles to use the appropriate rules.
 
 
-ac_ext=f90
+
+
+if test "$F90" = "xlf90"; then
+   defineflag="-WF,-Daardvark"
+else
+   defineflag="-Daardvark"
+fi
+
+
+
+ac_ext=$ac_save_ext
 ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
 
 old_ac_ext=$ac_ext
-ac_ext=F90
 old_F90=$F90
-F90="$F90 -Daardvark"
+F90="$F90 $defineflag"
 echo "$as_me:$LINENO: checking if Fortran 90 compiler performs preprocessing" >&5
 echo $ECHO_N "checking if Fortran 90 compiler performs preprocessing... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
@@ -2724,7 +2862,7 @@ program main
 
   implicit none
 #if zebra || aardvark
-  character(len=25) :: ch
+  character(len=25) :: ch  ! '"
 #endif
   ch="Does this test work? "// &
           "YES!"
@@ -2797,17 +2935,34 @@ fi
 done
 test -n "$CPP" || CPP="$CPP"
 
-   if test -z "$CPPFLAGS"; then
-     CPPFLAGS="-P -C -N"
+   if test -z "$FPPFLAGS"; then
+     FPPFLAGS="-P -C -N -traditional"
 
    fi
-   { ac_try='$CPP -Daardvark $CPPFLAGS conftest.$ac_ext conftest.f90'
+   ac_ext=bar
+   cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+  implicit none
+#if zebra || aardvark
+  character(len=25) :: ch  ! '"
+#endif
+  ch="Does this test work? "// &
+          "YES!"
+
+
+end program main
+
+_ACEOF
+   { ac_try='$CPP $defineflag $FPPFLAGS conftest.$ac_ext conftest.$old_ac_ext'
   { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
   (eval $ac_try) 2>&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }
    ac_ext=$old_ac_ext
+   F90=$old_F90
    rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
@@ -2826,8 +2981,8 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-{ echo "$as_me:$LINENO: WARNING: cpp output fails under fotrancompiler" >&5
-echo "$as_me: WARNING: cpp output fails under fotrancompiler" >&2;}
+{ echo "$as_me:$LINENO: WARNING: cpp output fails under fotran compiler" >&5
+echo "$as_me: WARNING: cpp output fails under fotran compiler" >&2;}
 
 fi
 rm -f conftest.$ac_objext
@@ -2837,7 +2992,9 @@ rm -f conftest.$ac_objext
 ac_ext=$old_ac_ext
 F90=$old_F90
 
+
 if test x != x"$CPP"; then
+   FPP=$CPP
    FRULE=.FRULE
 
    F90RULE=.F90RULE
@@ -2845,7 +3002,6 @@ if test x != x"$CPP"; then
    FRULECPP=.F.o
 
    F90RULECPP=.F90.o
-
 
 else
    FRULE=.F.o
@@ -2872,7 +3028,10 @@ echo "osname=$osname"
 # Check OS name
 
 if echo $osname | grep -i aix >/dev/null 2>&1; then
-   MACHDEFS="-DSYSAIX $MACHDEFS"
+   if test -z "$MACHDEFS"; then
+      MACHDEFS="-WF"
+   fi
+   MACHDEFS="$MACHDEFS,-DSYSAIX"
 fi
 if echo $osname | grep -i darwin >/dev/null 2>&1; then
    MACHDEFS="-DSYSDARWIN $MACHDEFS"
@@ -2905,9 +3064,26 @@ if echo $osname | grep -i unicos >/dev/null 2>&1; then
    MACHDEFS="-DSYSUNICOS $MACHDEFS"
 fi
 
+
+
+
 # Check compiler name
 case $F90 in
-xlf90) MACHDEFS="-DXLF $MACHDEFS";;
+xlf90)
+if test -z "$REAL8"; then
+   REAL8="-qrealsize=8"
+fi
+MACHDEFS="$MACHDEFS,-DXLF"
+if test -z "$FFLAGS"; then
+   FFLAGS="-qarch=auto -O2"
+fi
+if test -z "$F90FLAGS"; then
+  if test -z "$FPP"; then
+     F90FLAGS="-qsuffix=f=F90:cpp=F90"
+  else
+     F90FLAGS="-qsuffix=f=f90"
+  fi
+fi;;
 pgf90) MACHDEFS="-DPGI $MACHDEFS";;
 ftn) MACHDEFS="-DCRAY $MACHDEFS";;
 epcf90) MACHDEFS="-DEPC $MACHDEFS";;
@@ -3573,13 +3749,18 @@ s,@F90FLAGS@,$F90FLAGS,;t t
 s,@ac_ct_F90@,$ac_ct_F90,;t t
 s,@MPIF90@,$MPIF90,;t t
 s,@MPILIBS@,$MPILIBS,;t t
+s,@FC@,$FC,;t t
 s,@MUPDATE@,$MUPDATE,;t t
+s,@FPP@,$FPP,;t t
+s,@FPPFLAGS@,$FPPFLAGS,;t t
 s,@CPP@,$CPP,;t t
 s,@FRULE@,$FRULE,;t t
 s,@F90RULE@,$F90RULE,;t t
 s,@FRULECPP@,$FRULECPP,;t t
 s,@F90RULECPP@,$F90RULECPP,;t t
 s,@MACHDEFS@,$MACHDEFS,;t t
+s,@FFLAGS@,$FFLAGS,;t t
+s,@REAL8@,$REAL8,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -3816,10 +3997,14 @@ fi
 echo
 echo "### Output Variables: Make Sure These Are Correct! ###"
 echo "CC=$CC"
-echo "CPP=$CPP"
-echo "CPPFLAGS=$CPPFLAGS"
+echo "FPP=$FPP"
+echo "FPPFLAGS=$FPPFLAGS"
+echo "FC=$FC"
 echo "F90=$F90"
+echo "FFLAGS=$FFLAGS"
 echo "F90FLAGS=$F90FLAGS"
+echo "REAL8=$REAL8"
+echo "MPIF90=$MPIF90"
 echo "MPILIBS=$MPILIBS"
 echo "MACHDEFS=$MACHDEFS"
 echo "MUPDATE=$MUPDATE"
