ported script to intel fortran compiler

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -270,7 +270,7 @@ PACKAGE_VERSION='0.01'
 PACKAGE_STRING='MCT 0.01'
 PACKAGE_BUGREPORT=''
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT F90 F90FLAGS ac_ct_F90 MPIF90 MPILIBS FC FPP FPPFLAGS CPP FRULE F90RULE FRULECPP F90RULECPP MACHDEFS FFLAGS REAL8 BIT64 ENDIAN INCLUDE LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT F90 F90FLAGS ac_ct_F90 MPIF90 MPILIBS FC FPP FPPFLAGS FRULE F90RULE FRULECPP F90RULECPP MACHDEFS FFLAGS REAL8 BIT64 ENDIAN INCLUDEFLAG INCLUDEPATH LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -771,10 +771,14 @@ ac_env_ENDIAN_set=${ENDIAN+set}
 ac_env_ENDIAN_value=$ENDIAN
 ac_cv_env_ENDIAN_set=${ENDIAN+set}
 ac_cv_env_ENDIAN_value=$ENDIAN
-ac_env_INCLUDE_set=${INCLUDE+set}
-ac_env_INCLUDE_value=$INCLUDE
-ac_cv_env_INCLUDE_set=${INCLUDE+set}
-ac_cv_env_INCLUDE_value=$INCLUDE
+ac_env_INCLUDEFLAG_set=${INCLUDEFLAG+set}
+ac_env_INCLUDEFLAG_value=$INCLUDEFLAG
+ac_cv_env_INCLUDEFLAG_set=${INCLUDEFLAG+set}
+ac_cv_env_INCLUDEFLAG_value=$INCLUDEFLAG
+ac_env_INCLUDEPATH_set=${INCLUDEPATH+set}
+ac_env_INCLUDEPATH_value=$INCLUDEPATH
+ac_cv_env_INCLUDEPATH_set=${INCLUDEPATH+set}
+ac_cv_env_INCLUDEPATH_value=$INCLUDEPATH
 
 #
 # Report the --help message.
@@ -863,7 +867,8 @@ Some influential environment variables:
               REAL(KIND=8)
   BIT64       Fortran compiler flag for generating 64-bit objects
   ENDIAN      Fortran compiler flag for converting big-endian to little-endian
-  INCLUDE     Fortran compiler flag for specifying module search path
+  INCLUDEFLAG Fortran compiler flag for specifying module search path
+  INCLUDEPATH Additional library and module paths
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -1941,11 +1946,16 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 # Check for the Fortran compiler.
 if test -n "$F90FLAGS"; then
-   F90ONLYFLAGS="$F90FLAGS"
+   F90TEMPFLAGS="$F90FLAGS"
    F90FLAGS=""
-fi
 if test -n "$FFLAGS"; then
    F90FLAGS="$FFLAGS"
+fi
+else
+if test -n "$FFLAGS"; then
+   F90TEMPFLAGS=""
+   F90FLAGS="$FFLAGS"
+fi
 fi
 
 ac_ext=$ac_save_ext
@@ -1953,7 +1963,7 @@ ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
 ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
 ac_compiler_gnu=$ac_cv_f90_compiler_gnu
 if test -n "$ac_tool_prefix"; then
-  for ac_prog in f90 xlf90 pgf90 ftn frt epcf90 f95 xlf95 lf95 fort g95
+  for ac_prog in f90 xlf90 pgf90 ftn frt epcf90 f95 xlf95 lf95 ifc efc fort g95
   do
     # Extract the first word of "$ac_tool_prefix$ac_prog", so it can be a program name with args.
 set dummy $ac_tool_prefix$ac_prog; ac_word=$2
@@ -1995,7 +2005,7 @@ fi
 fi
 if test -z "$F90"; then
   ac_ct_F90=$F90
-  for ac_prog in f90 xlf90 pgf90 ftn frt epcf90 f95 xlf95 lf95 fort g95
+  for ac_prog in f90 xlf90 pgf90 ftn frt epcf90 f95 xlf95 lf95 ifc efc fort g95
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -2039,6 +2049,7 @@ done
 fi
 
 
+ac_ext=f90
 echo "$as_me:$LINENO: checking Fortran compiler source file extension" >&5
 echo $ECHO_N "checking Fortran compiler source file extension... $ECHO_C" >&6
 ac_ext=F90
@@ -2113,11 +2124,8 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
 echo "${ECHO_T}.f" >&6
 else
 
-{ { echo "$as_me:$LINENO: error: Cannot determine source file extension
-See \`config.log' for more details." >&5
-echo "$as_me: error: Cannot determine source file extension
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
+{ echo "$as_me:$LINENO: WARNING: Cannot determine source file extension" >&5
+echo "$as_me: WARNING: Cannot determine source file extension" >&2;}
 
 fi
 
@@ -2129,7 +2137,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:2132:" \
+echo "$as_me:2140:" \
      "checking for Fortran 90 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -2492,7 +2500,7 @@ _ACEOF
 # 1 to this macro) to the Fortran 90 compiler in order to get "version" output
 ac_save_F90FLAGS=$F90FLAGS
 F90FLAGS="$F90FLAGS $ac_version"
-(eval echo $as_me:2495: \"$ac_link\") >&5
+(eval echo $as_me:2503: \"$ac_link\") >&5
 ac_f90_version_output=`eval $ac_link 5>&1 2>&1 | grep -v 'Driving:'`
 echo "$ac_f90_version_output" >&5
 F90FLAGS=$ac_save_F90FLAGS
@@ -2852,73 +2860,18 @@ esac
 
 
 
-if test "$F90" = "xlf90"; then
-   defineflag="-WF,-Daardvark"
-else
-   defineflag="-Daardvark"
-fi
-
-
-
-ac_ext=$ac_save_ext
-ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
-ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
-ac_compiler_gnu=$ac_cv_f90_compiler_gnu
-
-old_ac_ext=$ac_ext
-old_F90=$F90
-F90="$F90 $defineflag"
-echo "$as_me:$LINENO: checking if Fortran 90 compiler performs preprocessing" >&5
-echo $ECHO_N "checking if Fortran 90 compiler performs preprocessing... $ECHO_C" >&6
-cat >conftest.$ac_ext <<_ACEOF
-
-program main
-
-  implicit none
-#if zebra || aardvark
-  character(len=25) :: ch  ! '
-#endif
-  ch="Does this test work? "// &
-          "YES!"
-
-
-end program main
-
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-   echo "$as_me:$LINENO: checking if C preprocessor can work with Fortran compiler" >&5
-echo $ECHO_N "checking if C preprocessor can work with Fortran compiler... $ECHO_C" >&6
-   echo
+if test -z "$FPP"; then
    for ac_prog in cpp
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_prog_CPP+set}" = set; then
+if test "${ac_cv_prog_FPP+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test -n "$CPP"; then
-  ac_cv_prog_CPP="$CPP" # Let the user override the test.
+  if test -n "$FPP"; then
+  ac_cv_prog_FPP="$FPP" # Let the user override the test.
 else
 as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
 for as_dir in $PATH
@@ -2927,7 +2880,7 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_prog_CPP="$ac_prog"
+    ac_cv_prog_FPP="$ac_prog"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
@@ -2936,25 +2889,47 @@ done
 
 fi
 fi
-CPP=$ac_cv_prog_CPP
-if test -n "$CPP"; then
-  echo "$as_me:$LINENO: result: $CPP" >&5
-echo "${ECHO_T}$CPP" >&6
+FPP=$ac_cv_prog_FPP
+if test -n "$FPP"; then
+  echo "$as_me:$LINENO: result: $FPP" >&5
+echo "${ECHO_T}$FPP" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
-  test -n "$CPP" && break
+  test -n "$FPP" && break
 done
-test -n "$CPP" || CPP="$CPP"
+test -n "$FPP" || FPP="$CPP"
 
-   if test -z "$FPPFLAGS"; then
-     FPPFLAGS="-P -C -N -traditional"
+fi
+if test -z "$FPPFLAGS"; then
+   FPPFLAGS="-P -C -N -traditional"
+fi
 
-   fi
-   ac_ext=bar
-   cat >conftest.$ac_ext <<_ACEOF
+if test "$F90" = "xlf90"; then
+   defineflag="-WF,-Daardvark"
+else
+   defineflag="-Daardvark"
+fi
+
+
+old_ac_ext=$ac_ext
+old_F90=$F90
+F90="$F90 $defineflag"
+
+echo "$as_me:$LINENO: checking if Fortran 90 compiler performs preprocessing" >&5
+echo $ECHO_N "checking if Fortran 90 compiler performs preprocessing... $ECHO_C" >&6
+if test "${ac_cv_f90_fpp_builtin+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+
+ac_ext=$ac_save_ext
+ac_compile='$F90 -c $F90FLAGS conftest.$ac_ext >&5'
+ac_link='$F90 -o conftest$ac_exeext $F90FLAGS $LD90FLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_f90_compiler_gnu
+
+cat >conftest.$ac_ext <<_ACEOF
 
 program main
 
@@ -2962,22 +2937,16 @@ program main
 #if zebra || aardvark
   character(len=25) :: ch  ! '
 #endif
-  ch="Does this test work? "// &
+  ch="Does this test &
+!Comment-Line
+          &work? "// &
           "YES!"
 
 
 end program main
 
 _ACEOF
-   { ac_try='$CPP $defineflag $FPPFLAGS conftest.$ac_ext conftest.$old_ac_ext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }
-   ac_ext=$old_ac_ext
-   F90=$old_F90
-   rm -f conftest.$ac_objext
+rm -f conftest.$ac_objext
 if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -2989,35 +2958,83 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
+  ac_cv_f90_fpp_builtin="yes"
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-{ echo "$as_me:$LINENO: WARNING: cpp output fails under fotran compiler" >&5
-echo "$as_me: WARNING: cpp output fails under fotran compiler" >&2;}
-
+ac_cv_f90_fpp_builtin="no"
 fi
 rm -f conftest.$ac_objext
 
 fi
+echo "$as_me:$LINENO: result: $ac_cv_f90_fpp_builtin" >&5
+echo "${ECHO_T}$ac_cv_f90_fpp_builtin" >&6
+
+echo "$as_me:$LINENO: checking if C preprocessor can work with Fortran compiler" >&5
+echo $ECHO_N "checking if C preprocessor can work with Fortran compiler... $ECHO_C" >&6
+if test "${ac_cv_f90_fpp_works+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_ext=bar
+cat >conftest.$ac_ext <<_ACEOF
+
+program main
+
+  implicit none
+#if zebra || aardvark
+  character(len=25) :: ch  ! '
+#endif
+  ch="Does this test &
+!Comment-Line
+          &work? "// &
+          "YES!"
+
+
+end program main
+
+_ACEOF
+if test -z "$FPP"; then
+{ echo "$as_me:$LINENO: WARNING: FPP is not defined" >&5
+echo "$as_me: WARNING: FPP is not defined" >&2;}
+fi
+{ ac_try='$FPP $defineflag $FPPFLAGS conftest.$ac_ext conftest.f90'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }
+ac_ext="f90"
+F90=$old_F90
 rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_f90_fpp_works="yes"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_f90_fpp_works="no"
+fi
+rm -f conftest.$ac_objext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_f90_fpp_works" >&5
+echo "${ECHO_T}$ac_cv_f90_fpp_works" >&6
+
 ac_ext=$old_ac_ext
 F90=$old_F90
 
 
-if test x != x"$CPP"; then
-   FPP=$CPP
-   FRULE=.FRULE
-
-   F90RULE=.F90RULE
-
-   FRULECPP=.F.o
-
-   F90RULECPP=.F90.o
-
-else
+if test "$ac_cv_f90_fpp_builtin" = "yes"; then
    FRULE=.F.o
 
    F90RULE=.F90.o
@@ -3026,6 +3043,23 @@ else
 
    F90RULECPP=.F90RULECPP
 
+fi
+
+if test "$ac_cv_f90_fpp_builtin" = "no"; then
+if test "$ac_cv_f90_fpp_works" = "no"; then
+   { echo "$as_me:$LINENO: WARNING: Fortran Source Preprocessing has failed" >&5
+echo "$as_me: WARNING: Fortran Source Preprocessing has failed" >&2;}
+fi
+if test "$ac_cv_f90_fpp_works" = "yes"; then
+   FRULE=.FRULE
+
+   F90RULE=.F90RULE
+
+   FRULECPP=.F.o
+
+   F90RULECPP=.F90.o
+
+fi
 fi
 
 # Checks OS, compiler and machine type
@@ -3037,10 +3071,7 @@ echo "hostname=$ac_hostname"
 echo "machinename=$machinename"
 echo "osname=$osname"
 
-if test -n "$F90ONLYFLAGS"; then
-   F90FLAGS="$F90ONLYFLAGS"
-fi
-
+F90FLAGS="$F90TEMPFLAGS"
 
 
 # Check OS name
@@ -3092,6 +3123,7 @@ fi
 
 
 
+
 # Check compiler name
 case $F90 in
 xlf90)
@@ -3123,11 +3155,17 @@ fi;;
 ftn)
 MACHDEFS="-DCPRCRAY $MACHDEFS"
 FFLAGS="-em $FFLAGS"
-if test -z "$INCLUDE"; then
-   INCLUDE="-p"
+if test -z "$INCLUDEFLAG"; then
+   INCLUDEFLAG="-p"
 fi;;
 epcf90) MACHDEFS="-DCPREPC $MACHDEFS";;
 lf95) MACHDEFS="-DCPRLAHEY $MACHDEFS";;
+ifc | efc)
+MACHDEFS="-DCPRINTEL $MACHDEFS"
+if test -z "$REAL8"; then
+   REAL8="-r8"
+fi
+FFLAGS="-w $FFLAGS";;
 fort) MACHDEFS="-DCPRCOMPAQ $MACHDEFS";;
 g95) MACHDEFS="-DCPRGNU $MACHDEFS";;
 esac
@@ -3137,9 +3175,6 @@ if echo $f90_version | grep -i nag >/dev/null 2>&1; then
 fi
 if echo $f90_version | grep -i absoft >/dev/null 2>&1; then
    MACHDEFS="-DCPRABSOFT $MACHDEFS"
-fi
-if echo $f90_version | grep -i intel >/dev/null 2>&1; then
-   MACHDEFS="-DCPRINTEL $MACHDEFS"
 fi
 if echo $f90_version | grep -i mipspro >/dev/null 2>&1; then
    MACHDEFS="-DCPRMIPSPRO $MACHDEFS"
@@ -3164,8 +3199,8 @@ if echo $f90_version | grep -i sx >/dev/null 2>&1; then
    fi
 fi
 
-if test -z "$INCLUDE"; then
-   INCLUDE="-I"
+if test -z "$INCLUDEFLAG"; then
+   INCLUDEFLAG="-I"
 fi
 
 cat >confcache <<\_ACEOF
@@ -3818,7 +3853,6 @@ s,@MPILIBS@,$MPILIBS,;t t
 s,@FC@,$FC,;t t
 s,@FPP@,$FPP,;t t
 s,@FPPFLAGS@,$FPPFLAGS,;t t
-s,@CPP@,$CPP,;t t
 s,@FRULE@,$FRULE,;t t
 s,@F90RULE@,$F90RULE,;t t
 s,@FRULECPP@,$FRULECPP,;t t
@@ -3828,7 +3862,8 @@ s,@FFLAGS@,$FFLAGS,;t t
 s,@REAL8@,$REAL8,;t t
 s,@BIT64@,$BIT64,;t t
 s,@ENDIAN@,$ENDIAN,;t t
-s,@INCLUDE@,$INCLUDE,;t t
+s,@INCLUDEFLAG@,$INCLUDEFLAG,;t t
+s,@INCLUDEPATH@,$INCLUDEPATH,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
 CEOF
@@ -4076,7 +4111,8 @@ echo "BIT64=$BIT64"
 echo "MPIF90=$MPIF90"
 echo "MPILIBS=$MPILIBS"
 echo "MACHDEFS=$MACHDEFS"
-echo "INCLUDE=$INCLUDE"
+echo "INCLUDEFLAG=$INCLUDEFLAG"
+echo "INCLUDEPATH=$INCLUDEPATH"
 echo
 
 
