Add gotm

diff --git a/src/core_ocean/Makefile b/src/core_ocean/Makefile
--- a/src/core_ocean/Makefile
+++ b/src/core_ocean/Makefile
@@ -6,12 +6,12 @@ $(info "EXCLUDE_INIT_MODE found")
 endif
 
 OCEAN_SHARED_INCLUDES = -I$(PWD)/../framework -I$(PWD)/../external/esmf_time_f90 -I$(PWD)/../operators
-OCEAN_SHARED_INCLUDES += -I$(PWD)/BGC -I$(PWD)/shared -I$(PWD)/analysis_members -I$(PWD)/cvmix/src/shared -I$(PWD)/mode_forward -I$(PWD)/mode_analysis
+OCEAN_SHARED_INCLUDES += -I$(PWD)/BGC -I$(PWD)/shared -I$(PWD)/analysis_members -I$(PWD)/cvmix/src/shared -I$(PWD)/gotm/build -I$(PWD)/mode_forward -I$(PWD)/mode_analysis
 ifneq "$(EXCLUDE_INIT_MODE)" "true"
 	OCEAN_SHARED_INCLUDES += -I$(PWD)/mode_init
 endif
 
-all: shared libcvmix analysis_members libBGC
+all: shared libcvmix analysis_members libBGC libgotm
 	(cd mode_forward; $(MAKE) FCINCLUDES="$(FCINCLUDES) $(OCEAN_SHARED_INCLUDES)" all )
 	(cd mode_analysis; $(MAKE) FCINCLUDES="$(FCINCLUDES) $(OCEAN_SHARED_INCLUDES)" all )
 ifneq "$(EXCLUDE_INIT_MODE)" "true"
@@ -72,11 +72,22 @@ libBGC:
 		(echo "Missing core_ocean/BGC/.git, did you forget to 'git submodule update --init --recursive' ?"; exit 1) \
 	fi
 
-shared: libcvmix libBGC
+libgotm:
+	if [ -e gotm/.git ]; then \
+		if [ -e gotm/build ]; then \
+			(cd gotm/build; make) \
+		else \
+			(mkdir gotm/build; cd gotm/build; cmake ../src -DGOTM_BUILD_LIBRARIES_ONLY=true -DGOTM_USE_FABM=false -DGOTM_USE_NetCDF=false -DCMAKE_Fortran_COMPILER="$(FC)" -DCMAKE_Fortran_FLAGS="$(FCFLAGS)"; make) \
+		fi \
+	else \
+		(pwd ; echo "Missing core_ocean/gotm/.git, did you forget to 'git submodule update --init --recursive' ?"; exit 1) \
+	fi
+
+shared: libcvmix libBGC libgotm
 	(cd shared; $(MAKE) FCINCLUDES="$(FCINCLUDES) $(OCEAN_SHARED_INCLUDES)")
 
-analysis_members: libcvmix shared
-	( cd analysis_members; $(MAKE) FCINCLUDES="$(FCINCLUDES) $(OCEAN_SHARED_INCLUDES)" CPPFLAGS="$(CPPFLAGS)" CPPINCLUDES="$(CPPINCLUDES)" all ) 
+analysis_members: libcvmix shared libgotm
+	( cd analysis_members; $(MAKE) FCINCLUDES="$(FCINCLUDES) $(OCEAN_SHARED_INCLUDES)" CPPFLAGS="$(CPPFLAGS)" CPPINCLUDES="$(CPPINCLUDES)" all )
 
 clean:
 	if [ -e cvmix/.git ]; then \
@@ -87,6 +98,9 @@ clean:
 	fi
 	if [ -e BGC/.git ]; then \
 		(cd BGC; make clean) \
+	fi
+	if [ -e gotm/.git ]; then \
+		($(RM) -r gotm/build) \
 	fi
 	(cd mode_forward; $(MAKE) clean)
 	(cd mode_analysis; $(MAKE) clean)
