Overwrite old baselines if user asked for that
[BFB]

diff --git a/scripts/Tools/testcase_setup b/scripts/Tools/testcase_setup
--- a/scripts/Tools/testcase_setup
+++ b/scripts/Tools/testcase_setup
@@ -437,23 +437,14 @@ my $testcase_end = <<'END_TEST';
        endif
 
        if ("$continue_generate" == 'yes') then
-          if ( -e $BASEGEN_DIR/cpl.log ) then
-	     echo "WARNING:  component model data already exists - WILL NOT OVERWRITE " >>& $TESTSTATUS_LOG
-	     echo "" >>& $TESTSTATUS_LOG
-	     echo "GFAIL:  component model data already exists " >>& $TESTSTATUS_OUT
-	     set continue_generate = 'no'
-	  endif
-       endif
-
-       if ("$continue_generate" == 'yes') then
           ${SCRIPTSROOT}/Tools/component_compgen_baseline.sh -baseline_dir $BASEGEN_DIR -test_dir $RUNDIR -generate_tag $BASEGEN_NAME -testcase $CASE -testcase_base $CASEBASEID >>& $TESTSTATUS_OUT
 
 	  # save last coupler log file to baseline directory
-	  cp $CplLogFile $BASEGEN_DIR/cpl.log || echo "WARNING: could not copy $CplLogFile to $BASEGEN_DIR " >>& $TESTSTATUS_LOG
+	  cp -f $CplLogFile $BASEGEN_DIR/cpl.log || echo "WARNING: could not copy $CplLogFile to $BASEGEN_DIR " >>& $TESTSTATUS_LOG
 	  chmod ug+w,a+r $BASEGEN_DIR/cpl.log
 	  
 	  if ($?CPLPROF_GENCMP) then # this variable is set in the test script
-	     cp $CPLPROF_GENCMP $BASEGEN_DIR/timing_summary || echo "WARNING: could not copy $CPLPROF_GENCMP to $BASEGEN_CPLPROFFILE" >>& $TESTSTATUS_LOG
+	     cp -f $CPLPROF_GENCMP $BASEGEN_DIR/timing_summary || echo "WARNING: could not copy $CPLPROF_GENCMP to $BASEGEN_CPLPROFFILE" >>& $TESTSTATUS_LOG
 	     chmod ug+w,a+r $BASEGEN_DIR/timing_summary
 	  endif
 
@@ -553,7 +544,7 @@ my $testcase_end = <<'END_TEST';
 
    if ( "$GENERATE_BASELINE" == "TRUE" ) then
       if (-e $BASEGEN_DIR) then
-         cp $TESTSTATUS_LOG ${BASEGEN_DIR}/${TESTSTATUS_LOG:t}
+         cp -f $TESTSTATUS_LOG ${BASEGEN_DIR}/${TESTSTATUS_LOG:t}
          chmod ug+w,a+r ${BASEGEN_DIR}/${TESTSTATUS_LOG:t}
        endif
    endif
