Importing cesm1_3_beta10

diff --git a/scripts/ccsm_utils/Tools/ccsm_getenv b/scripts/ccsm_utils/Tools/ccsm_getenv
--- a/scripts/ccsm_utils/Tools/ccsm_getenv
+++ b/scripts/ccsm_utils/Tools/ccsm_getenv
@@ -8,18 +8,21 @@ if ($status != 0) then
 endif
 
 # Source the result of the env files - in the following order
-foreach i (env_case.xml env_run.xml env_mach_pes.xml env_build.xml)
-  source $i:r || exit -1
-  if ($status != 0) then
-     echo "ccsm_getenv error: problem sourcing $i:r" 
-     exit -2
-  endif 
-  rm $i:r    
-  if ($status != 0) then
-     echo "ccsm_getenv error: problem removing $i:r" 
-     exit -3
+foreach i (env_case.xml  env_build.xml env_run.xml env_mach_pes.xml env_test.xml )
+  if ( -e $i ) then
+    source $i:r || exit -1
+    if ($status != 0) then
+       echo "ccsm_getenv error: problem sourcing $i:r" 
+       exit -2
+    endif 
+    rm $i:r    
+    if ($status != 0) then
+       echo "ccsm_getenv error: problem removing $i:r" 
+       exit -3
+    endif
   endif
 end
+
 
 # Source env_mach_specific 
 source env_mach_specific
diff --git a/scripts/ccsm_utils/Tools/component_gen_comp b/scripts/ccsm_utils/Tools/component_gen_comp
--- a/scripts/ccsm_utils/Tools/component_gen_comp
+++ b/scripts/ccsm_utils/Tools/component_gen_comp
@@ -78,12 +78,12 @@
 #
 # - test PASS for generate, with only one possible extension (e.g., for a cpl test)
 #
-# - test BFAIL1 for generate due to no hist file for any extension
-#   - should get a single BFAIL1 message
+# - test BFAIL_NA for generate due to no hist file for any extension
+#   - should get a single BFAIL_NA message
 #
-# - test BFAIL1 for h0, PASS for h1: should just see a PASS message
+# - test BFAIL_NA for h0, PASS for h1: should just see a PASS message
 #
-# - test BFAIL1 for generate, with only one possible extension (e.g., for a cpl test)
+# - test BFAIL_NA for generate, with only one possible extension (e.g., for a cpl test)
 #
 # - test with multiple history files for the component: make sure the
 #   right one is chosen
@@ -102,14 +102,14 @@
 #
 # - test PASS for compare, with only one possible extension (e.g., for a cpl test)
 #
-# - test BFAIL1 for compare due to no hist file for any extension in either test case or baseline
-#   - should get a single BFAIL1 message
+# - test BFAIL_NA for compare due to no hist file for any extension in either test case or baseline
+#   - should get a single BFAIL_NA message
 #
-# - test BFAIL1 for h0, PASS for h1: should just see a PASS message
+# - test BFAIL_NA for h0, PASS for h1: should just see a PASS message
 #
-# - test BFAIL1 for compare, with only one possible extension (e.g., for a cpl test)
+# - test BFAIL_NA for compare, with only one possible extension (e.g., for a cpl test)
 #
-# - test BFAIL2 for compare due to no baseline directory
+# - test BFAIL for compare due to no baseline directory
 #
 # - test FAIL for compare due to no hist file (can do this by
 # temporarily removing a history file from one test directory)
@@ -229,27 +229,27 @@ function get_info {
     echo $status_and_info | cut -d ':' -f 2-
 }
 
-# Update a variable saying whether everything we have seen is a BFAIL1
+# Update a variable saying whether everything we have seen is a BFAIL_NA
 # Inputs:
 #   - status of the last comparison / generate
-#   - all_bfail1: 1 if everything so far has been a BFAIL1, 0 if not
+#   - all_bfail_na: 1 if everything so far has been a BFAIL_NA, 0 if not
 # Output:
-#   - 1 if everything so far has been a BFAIL1, including the latest
+#   - 1 if everything so far has been a BFAIL_NA, including the latest
 #     comparison; 0 if not
-function still_all_bfail1 {
+function still_all_bfail_na {
     local status="$1"
-    local all_bfail1=$2
+    local all_bfail_na=$2
 
-    if [ $all_bfail1 -eq 0 ]; then
+    if [ $all_bfail_na -eq 0 ]; then
 	echo 0
-    elif [ $all_bfail1 -eq 1 ]; then
-	if [ "$status" = "BFAIL1" ]; then
+    elif [ $all_bfail_na -eq 1 ]; then
+	if [ "$status" = "BFAIL_NA" ]; then
 	    echo 1
 	else
 	    echo 0
 	fi
     else
-	echo "Unexpected value for all_bfail1: $all_bfail1" 1>&2
+	echo "Unexpected value for all_bfail_na: $all_bfail_na" 1>&2
 	exit 1
     fi
 }
@@ -276,7 +276,7 @@ function print_status {
     fi    
 
     # Print formatted test result
-    printf '%-6s %s %s\n' "$status" "${testcase}.${qualifier}" "$info_str"
+    printf '%-8s %s %s\n' "$status" "${testcase}.${qualifier}" "$info_str"
 }
 
 #======================================================================
@@ -377,14 +377,14 @@ fi
 #----------------------------------------------------------------------
 
 echo "Possible test result outcomes:"
-echo "  UNDEF  - undefined result (may be an error in the script)"
-echo "  BFAIL1 - compare:  no history file in baseline or in test case"
-echo "         - generate: no history file in test case"
-echo "  BFAIL2 - compare:  no baseline history file, despite existence of history file in test case"
-echo "         - generate: error creating baseline directory or copying baseline file into place"
-echo "  FAIL   - compare test fails (including: baseline exists but no history file for the test case)"
-echo "           (see *.cprnc.out in the test's run directory for details)"
-echo "  PASS   - test passes"
+echo "  UNDEF    - undefined result (may be an error in the script)"
+echo "  BFAIL_NA - compare:  no history file in baseline or in test case"
+echo "           - generate: no history file in test case"
+echo "  BFAIL    - compare:  no baseline history file, despite existence of history file in test case"
+echo "           - generate: error creating baseline directory or copying baseline file into place"
+echo "  FAIL     - compare test fails (including: baseline exists but no history file for the test case)"
+echo "             (see *.cprnc.out in the test's run directory for details)"
+echo "  PASS     - test passes"
 echo ""
 
 #----------------------------------------------------------------------
@@ -416,15 +416,15 @@ for testcase in $tests; do
     rundir=${runloc}/${testcase}/run
 
     #------------------------------------------------------------------
-    # Initialize variables tracking whether all results are BFAIL1
+    # Initialize variables tracking whether all results are BFAIL_NA
     #------------------------------------------------------------------
-    # For both compare & generate, BFAIL1 is acceptable unless it
+    # For both compare & generate, BFAIL_NA is acceptable unless it
     # occurs for all possible history file extensions. Thus, we only
-    # print a BFAIL1 result if it occurs for all history file
+    # print a BFAIL_NA result if it occurs for all history file
     # extensions. All other status options (PASS, FAIL, and other
     # types of BFAIL) are printed for each history file extension.
-    compare_all_bfail1=1
-    generate_all_bfail1=1
+    compare_all_bfail_na=1
+    generate_all_bfail_na=1
 
     #------------------------------------------------------------------
     # Loop over history file extensions
@@ -454,8 +454,8 @@ for testcase in $tests; do
 	    compare_result=`${tools_dir}/component_compare.sh  -baseline_dir "$baseline_dir" -baseline_hist "$baseline_hist" -test_dir "$rundir" -test_hist "$test_hist"`
 	    compare_status=`get_status "$compare_result"`
 	    compare_info=`get_info "$compare_result"`
-	    compare_all_bfail1=`still_all_bfail1 $compare_status $compare_all_bfail1`
-	    if [ "$compare_status" != "BFAIL1" ]; then
+	    compare_all_bfail_na=`still_all_bfail_na $compare_status $compare_all_bfail_na`
+	    if [ "$compare_status" != "BFAIL_NA" ]; then
 		print_status "$compare_status" "$compare_info" "$testcase_base" "compare_hist.${compare_tag}.$model.$extension"
 	    fi
 	fi
@@ -468,19 +468,19 @@ for testcase in $tests; do
 	    generate_result=`${tools_dir}/component_generate.sh -baseline_dir "$baseline_dir" -baseline_hist "$baseline_hist" -test_dir "$rundir" -test_hist "$test_hist"`
 	    generate_status=`get_status "$generate_result"`
 	    generate_info=`get_info "$generate_result"`
-	    generate_all_bfail1=`still_all_bfail1 $generate_status $generate_all_bfail1`
-	    if [ "$generate_status" != "BFAIL1" ]; then
+	    generate_all_bfail_na=`still_all_bfail_na $generate_status $generate_all_bfail_na`
+	    if [ "$generate_status" != "BFAIL_NA" ]; then
 		print_status "$generate_status" "$generate_info" "$testcase_base" "generate.$model.$extension"
 	    fi
 	fi
     done  # loop over history file extensions
 
-    if [ -n "$compare_tag" -a $compare_all_bfail1 -eq 1 ]; then
-	print_status "BFAIL1" "encountered BFAIL1 for all possible history extensions" "$testcase_base" "compare_hist.${compare_tag}.$model"
+    if [ -n "$compare_tag" -a $compare_all_bfail_na -eq 1 ]; then
+	print_status "BFAIL_NA" "encountered BFAIL_NA for all possible history extensions" "$testcase_base" "compare_hist.${compare_tag}.$model"
     fi
     
-    if [ -n "$generate_tag" -a $generate_all_bfail1 -eq 1 ]; then
-	print_status "BFAIL1" "encountered BFAIL1 for all possible history extensions" "$testcase_base" "generate.$model"
+    if [ -n "$generate_tag" -a $generate_all_bfail_na -eq 1 ]; then
+	print_status "BFAIL_NA" "encountered BFAIL_NA for all possible history extensions" "$testcase_base" "generate.$model"
     fi
 done
 
diff --git a/scripts/ccsm_utils/Tools/testcase_end b/scripts/ccsm_utils/Tools/testcase_end
--- a/scripts/ccsm_utils/Tools/testcase_end
+++ b/scripts/ccsm_utils/Tools/testcase_end
@@ -26,15 +26,15 @@ endif
 # Generate new baseline for regression testing
 #======================================================================
 set genstatus = "UNDEF"
-
-set CplHistDir = $RUNDIR
-set CplHistFileName = `cd $CplHistDir; ls -1t $CASE.cpl.hi*.nc | head -1 `
-if (${CplHistFileName} == '') then
-  set CplHistDir = $DOUT_S_ROOT/cpl/hist
+if ( "$GENERATE_BASELINE" == "TRUE" ) then
+  set CplHistDir = $RUNDIR
   set CplHistFileName = `cd $CplHistDir; ls -1t $CASE.cpl.hi*.nc | head -1 `
+  if (${CplHistFileName} == '') then
+    set CplHistDir = $DOUT_S_ROOT/cpl/hist
+    set CplHistFileName = `cd $CplHistDir; ls -1t $CASE.cpl.hi*.nc | head -1 `
+  endif
+  set CplHistFile = $CplHistDir/$CplHistFileName
 endif
-set CplHistFile = $CplHistDir/$CplHistFileName
-
 echo " xyz " >! grep_a_test_file
 set grepa = "-a"
 grep -a xyz grep_a_test_file >& /dev/null
@@ -44,7 +44,7 @@ endif
 rm grep_a_test_file
 
 set memleak = ""
-if ( $?DETECT_MEMORY_LEAK) then 
+if ( $?DETECT_MEMORY_LEAK ) then 
  if ($basestatus == "PASS") then
    if ( $?CPLLOG_INIT ) then
     echo "Comparing memory highwater marks for consecutive days in $CPLLOG_INIT" >>& $TESTSTATUS_LOG
@@ -62,7 +62,7 @@ if ( $?DETECT_MEMORY_LEAK) then
  endif
 endif  
 
-if ( $?GENERATE_BASELINE ) then
+if ( "$GENERATE_BASELINE" == "TRUE" ) then
   if ($basestatus == "PASS") then
     set genstatus = "PASS "
     if ! ( -d $BASELINE_ROOT ) then
@@ -159,7 +159,7 @@ set pesmaxmem_incr = ""
 set tput_decr = ""
 set tput_percent_decr = ""
 
-if ( $?COMPARE_BASELINE ) then
+if ( "$COMPARE_BASELINE" == "TRUE" ) then
   if ! ( -d $BASELINE_ROOT ) then
     echo "ERROR in ${0}:  directory $BASELINE_ROOT does not exist " >>& $TESTSTATUS_LOG
     set genstatus = "BFAIL "
@@ -189,7 +189,7 @@ if ( $?COMPARE_BASELINE ) then
       echo "hist file comparison is $compstatus" >>& $TESTSTATUS_LOG
       echo "$compstatus ${CASEBASEID}.compare_hist.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
       if ($basestatus == "PASS") then
-        if( $?COMPARE_MEMORY ) then 
+        if( "$COMPARE_MEMORY" == "TRUE" ) then 
           echo "Comparing pes max memory value with baseline pes max memory value" >>& $TESTSTATUS_LOG 
           set baseline_CplLogFile = ` grep $grepa startup $BASECMP_DIR/cpl.log* | awk -F ":" '{ print $1 }'`
           echo "Comparing log files $CPLLOG_INIT and $baseline_CplLogFile" >>& $TESTSTATUS_LOG 
@@ -204,7 +204,7 @@ if ( $?COMPARE_BASELINE ) then
             echo "$compstatus ${CASEBASEID}.memcomp.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
           endif
         endif  
-        if ( $?COMPARE_THROUGHPUT ) then
+        if ( "$COMPARE_THROUGHPUT" == "TRUE" ) then
           echo "Comparing throughput value with baseline throughput value" >>& $TESTSTATUS_LOG
           set baseline_CplLogFile = ` grep $grepa startup $BASECMP_DIR/cpl.log* | awk -F ":" '{ print $1 }'`
           echo "Comparing log files $CplLogFile and $baseline_CplLogFile" >>& $TESTSTATUS_LOG
@@ -224,11 +224,59 @@ if ( $?COMPARE_BASELINE ) then
   endif
 endif
 
+#======================================================================
+# Run the component gen compare to compare component history files
+# (Currently only recognizes cism, clm2 and could be used for cpl as well)
+# (Could be easily extended to recognize other components with the history extension list)
+#======================================================================
+set extension_list = ""
+if ( $MODEL_GEN_COMP != "UNSET" ) then
+   if      ( "$MODEL_GEN_COMP" == "cism" ) then
+      set extension_list = "h"
+   else if ( "$MODEL_GEN_COMP" == "clm2" ) then
+      set extension_list = "h0 h1 h2 h3 h4 h5"
+   else if ( "$MODEL_GEN_COMP" == "cpl" ) then
+      set extension_list = "hi"
+   endif
+   foreach type ( compare_hist generate )
+      set all_bfail=1
+      foreach extension ( $extension_list )
+         set test_hist=`cd $RUNDIR; ls -1 ${CASE}.${MODEL_GEN_COMP}*.${extension}*.nc | tail -1`
+         set base_hist="${MODEL_GEN_COMP}.${extension}.nc"
+         set ran="nope"
+         if ( "$type" == "compare_hist" && $?BASECMP_NAME ) then
+            set ran="yep"
+            $CASETOOLS/component_compare.sh -baseline_dir $BASECMP_DIR \
+             -test_dir $RUNDIR -test_hist "$test_hist" -baseline_hist $base_hist >> $TESTSTATUS_LOG
+         endif
+         if ( "$type" == "generate" && $?BASEGEN_NAME ) then
+            set ran="yep"
+            $CASETOOLS/component_generate.sh -baseline_dir $BASEGEN_DIR \
+             -test_dir $RUNDIR -test_hist "$test_hist" -baseline_hist $base_hist >> $TESTSTATUS_LOG
+         endif
+         if ( "$ran" == "yep" ) then
+            set compstatus = `tail -1 $TESTSTATUS_LOG | cut -d ':' -f 1`
+            if ( "$compstatus" != "BFAIL_NA" ) then
+               set all_bfail=0
+               echo "$compstatus ${CASEBASEID}.${MODEL_GEN_COMP}.${extension}.${type}.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
+            endif
+         endif
+      end
+      if ( $all_bfail  == 1 && "$ran" == "yep" ) then
+         echo "BFAIL_NA ${CASEBASEID}.${MODEL_GEN_COMP}.all_extensions.${type}.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
+      endif
+   end
+endif
+
 if ( $?CPLLOG_INIT) then
    if (-e $CPLLOG_INIT) then
       echo " " >>& $TESTSTATUS_LOG
       echo "=======================" >>& $TESTSTATUS_LOG
-      tail -20 $CPLLOG_INIT >>& $TESTSTATUS_LOG
+      if( "$CPLLOG_INIT" =~ /.gz/ ) then
+        zcat $CPLLOG_INIT | tail -15  >>& $TESTSTATUS_LOG
+      else
+        tail -15 $CPLLOG_INIT  >>& $TESTSTATUS_LOG
+      endif
       echo "=======================" >>& $TESTSTATUS_LOG
       echo " " >>& $TESTSTATUS_LOG
 
@@ -243,9 +291,9 @@ if ( $?CPLLOG_INIT) then
       if ( $?BASEGEN_NAME) then
         set tag = `echo $BASEGEN_NAME`
       endif
-      set tput = `grep "# simulated years " $CPLLOG_INIT | cut -c 63-72`
-      set memh = `grep "max memory highwater" $CPLLOG_INIT | cut -c 63-72`
-      set memr = `grep "max memory last usage" $CPLLOG_INIT | cut -c 63-72`
+      set tput = `zgrep "# simulated years " $CPLLOG_INIT | cut -c 63-72`
+      set memh = `zgrep "max memory highwater" $CPLLOG_INIT | cut -c 63-72`
+      set memr = `zgrep "max memory last usage" $CPLLOG_INIT | cut -c 63-72`
       echo "$bbb2" >>& $TESTSTATUS_LOG
       echo "CHECK ${CASEBASEID}.perf npes=$npes tput=$tput memh=$memh memr=$memr tag=$tag" >>& $TESTSTATUS_LOG
       if ( "${CASEBASEID}" =~ ERT* || "${CASEBASEID}" =~ PFS* ) then
@@ -274,7 +322,7 @@ endif
 # Clean up
 #======================================================================
 
-if ( $?CLEANUP ) then
+if ( "$CLEANUP" == "TRUE" ) then
   if ($basestatus == "PASS") then
     if ($compstatus != "FAIL") then
        rm -r -f $EXEROOT*/atm          >& /dev/null
@@ -308,7 +356,7 @@ else
 endif
 
 
-if ( $?GENERATE_BASELINE ) then
+if ( "$GENERATE_BASELINE" == "TRUE" ) then
   if (-e $BASEGEN_DIR) then
     cp $TESTSTATUS_LOG ${BASEGEN_DIR}/${TESTSTATUS_LOG:t}
     chmod ug+w,a+r ${BASEGEN_DIR}/${TESTSTATUS_LOG:t}
