Bring clm4_5_1_r097 into ACME
Recipe:

svn export https://svn-ccsm-models.cgd.ucar.edu/clm2/trunk_tags/clm4_5_1_r097

git clone git@github.com:bishtgautam/ACME.git ACME-bishtgautam
cd ACME-bishtgautam

git checkout b7663ced4df893deaa8c8cfec5d43a39807c846a
git branch bishtgautam/lnd/clm4.5.097

rsync -r --delete ../clm4_5_1_r097/models/lnd/clm models/lnd
rsync -r --delete ../clm4_5_1_r097/scripts ./
rsync -r --delete ../clm4_5_1_r097/models/atm/datm models/atm
rsync -r --delete ../clm4_5_1_r097/models/csm_share models

diff --git a/scripts/ccsm_utils/Tools/cesm_submit b/scripts/ccsm_utils/Tools/cesm_submit
--- a/scripts/ccsm_utils/Tools/cesm_submit
+++ b/scripts/ccsm_utils/Tools/cesm_submit
@@ -1,8 +1,18 @@
 #! /bin/csh -f
 
 source ./Tools/ccsm_getenv || exit -2
-
-./check_case || echo "check_case failed" && exit -2
+set NEEDS_CHECKCASE=1
+if( $?TESTCASE ) then
+  if( $TESTCASE == "SBN" ) then
+    set BATCHSUBMIT=' '
+    echo "emptying BATCHSUBMIT for SBN test"
+	set NEEDS_CHECKCASE=0
+  endif
+endif
+if($NEEDS_CHECKCASE == 1) then
+	echo "checking case.."
+    ./check_case || echo "check_case failed" && exit -2
+endif
 set sdate = `date +"%Y-%m-%d %H:%M:%S"`
 
 if (-e ${CASE}.test) then
