updates the testlist and testcase_begin/end files to be same as 202ab46.

diff --git a/scripts/ccsm_utils/Tools/testcase_end b/scripts/ccsm_utils/Tools/testcase_end
--- a/scripts/ccsm_utils/Tools/testcase_end
+++ b/scripts/ccsm_utils/Tools/testcase_end
@@ -10,8 +10,8 @@
 if ( ${CASE} =~ *_IOP* && $basestatus == "PASS") then
   gunzip $CASEROOT/logs/cpl.log*.gz
   set cpllogi = `ls -1t $CASEROOT/logs/cpl.log* | head -1`
-  gunzip $CASEROOT/../${iopbase_case}/logs/cpl.log*.gz
-  set cpllogn = `ls -1t $CASEROOT/../${iopbase_case}/logs/cpl.log* | head -1`
+  gunzip $CASEROOT/${iopbase_case}/logs/cpl.log*.gz
+  set cpllogn = `ls -1t $CASEROOT/${iopbase_case}/logs/cpl.log* | head -1`
   $CASETOOLS/check_exactrestart.pl $cpllogn $cpllogi >>& $TESTSTATUS_LOG
   set pass = `tail -1 $TESTSTATUS_LOG | grep PASS | wc -l`
   if ( $pass != 0 ) then
@@ -74,69 +74,56 @@ if ( "$GENERATE_BASELINE" == "TRUE" ) then
     endif
 
     # coupler log file
-    if ( -e $BASEGEN_CPLLOGFILE ) then
-      echo "ERROR in ${0}:  baseline log file $BASEGEN_CPLLOGFILE already exists."
-      set genstatus = "FAIL "
-    else
-      cp $CPLLOG_GENCMP $BASEGEN_CPLLOGFILE || echo "ERROR in ${0}:  could not copy $CPLLOG_GENCMP to $BASEGEN_CPLLOGFILE " >>& $TESTSTATUS_LOG
-      chmod ug+w,a+r $BASEGEN_CPLLOGFILE
+    cp -f $CPLLOG_GENCMP $BASEGEN_CPLLOGFILE || echo "ERROR in ${0}:  could not copy $CPLLOG_GENCMP to $BASEGEN_CPLLOGFILE " >>& $TESTSTATUS_LOG
+    chmod ug+w,a+r $BASEGEN_CPLLOGFILE
 
-      # save extra files
-      if ( $?BASEGEN_FILE01 ) then
-        cp $BASEGEN_FILE01 $BASEGEN_DIR/${BASEGEN_FILE01:t}
-      endif
-      if ( $?BASEGEN_FILE02 ) then
-        cp $BASEGEN_FILE02 $BASEGEN_DIR/${BASEGEN_FILE02:t}
-      endif
-      if ( $?BASEGEN_FILE03 ) then
-        cp $BASEGEN_FILE03 $BASEGEN_DIR/${BASEGEN_FILE03:t}
-      endif
-      if ( $?BASEGEN_FILE04 ) then
-        cp $BASEGEN_FILE04 $BASEGEN_DIR/${BASEGEN_FILE04:t}
-      endif
-      if ( $?BASEGEN_FILE05 ) then
-        cp $BASEGEN_FILE05 $BASEGEN_DIR/${BASEGEN_FILE05:t}
-      endif
-      if ( $?BASEGEN_FILE06 ) then
-        cp $BASEGEN_FILE06 $BASEGEN_DIR/${BASEGEN_FILE06:t}
-      endif
-      if ( $?BASEGEN_FILE07 ) then
-        cp $BASEGEN_FILE07 $BASEGEN_DIR/${BASEGEN_FILE07:t}
-      endif
-      if ( $?BASEGEN_FILE08 ) then
-        cp $BASEGEN_FILE08 $BASEGEN_DIR/${BASEGEN_FILE08:t}
-      endif
-      if ( $?BASEGEN_FILE09 ) then
-        cp $BASEGEN_FILE09 $BASEGEN_DIR/${BASEGEN_FILE09:t}
-      endif
-      if ( $?BASEGEN_FILE10 ) then
-        cp $BASEGEN_FILE10 $BASEGEN_DIR/${BASEGEN_FILE10:t}
-      endif
-      if ( $?BASEGEN_FILE11 ) then
-        cp $BASEGEN_FILE11 $BASEGEN_DIR/${BASEGEN_FILE11:t}
-      endif
-      if ( $?BASEGEN_FILE12 ) then
-        cp $BASEGEN_FILE12 $BASEGEN_DIR/${BASEGEN_FILE12:t}
-      endif
-      chmod ug+w,a+r $BASEGEN_DIR/*
+    # save extra files
+    if ( $?BASEGEN_FILE01 ) then
+      cp $BASEGEN_FILE01 $BASEGEN_DIR/${BASEGEN_FILE01:t}
     endif
+    if ( $?BASEGEN_FILE02 ) then
+      cp $BASEGEN_FILE02 $BASEGEN_DIR/${BASEGEN_FILE02:t}
+    endif
+    if ( $?BASEGEN_FILE03 ) then
+      cp $BASEGEN_FILE03 $BASEGEN_DIR/${BASEGEN_FILE03:t}
+    endif
+    if ( $?BASEGEN_FILE04 ) then
+      cp $BASEGEN_FILE04 $BASEGEN_DIR/${BASEGEN_FILE04:t}
+    endif
+    if ( $?BASEGEN_FILE05 ) then
+      cp $BASEGEN_FILE05 $BASEGEN_DIR/${BASEGEN_FILE05:t}
+    endif
+    if ( $?BASEGEN_FILE06 ) then
+      cp $BASEGEN_FILE06 $BASEGEN_DIR/${BASEGEN_FILE06:t}
+    endif
+    if ( $?BASEGEN_FILE07 ) then
+      cp $BASEGEN_FILE07 $BASEGEN_DIR/${BASEGEN_FILE07:t}
+    endif
+    if ( $?BASEGEN_FILE08 ) then
+      cp $BASEGEN_FILE08 $BASEGEN_DIR/${BASEGEN_FILE08:t}
+    endif
+    if ( $?BASEGEN_FILE09 ) then
+      cp $BASEGEN_FILE09 $BASEGEN_DIR/${BASEGEN_FILE09:t}
+    endif
+    if ( $?BASEGEN_FILE10 ) then
+      cp $BASEGEN_FILE10 $BASEGEN_DIR/${BASEGEN_FILE10:t}
+    endif
+    if ( $?BASEGEN_FILE11 ) then
+      cp $BASEGEN_FILE11 $BASEGEN_DIR/${BASEGEN_FILE11:t}
+    endif
+    if ( $?BASEGEN_FILE12 ) then
+      cp $BASEGEN_FILE12 $BASEGEN_DIR/${BASEGEN_FILE12:t}
+    endif
+    chmod ug+w,a+r $BASEGEN_DIR/*
 
     # coupler history file
-    if ( -e $BASEGEN_CPLHISTFILE ) then
-      echo "ERROR in ${0}:  baseline history file $BASEGEN_CPLHISTFILE already exists."
-    else
-      cp $CplHistFile $BASEGEN_CPLHISTFILE || echo "ERROR in ${0}:  could not copy $CplHistFile to $BASEGEN_CPLHISTFILE " >>& $TESTSTATUS_LOG
-      chmod ug+w,a+r $BASEGEN_CPLHISTFILE
-    endif
+    cp -f $CplHistFile $BASEGEN_CPLHISTFILE || echo "ERROR in ${0}:  could not copy $CplHistFile to $BASEGEN_CPLHISTFILE " >>& $TESTSTATUS_LOG
+    chmod ug+w,a+r $BASEGEN_CPLHISTFILE
 
     # coupler timing file
-    if ( -e $BASEGEN_CPLPROFFILE ) then
-      echo "ERROR in ${0}:  baseline timing file $BASEGEN_CPLPROFFILE already exists."
-    else
-      if ($?CPLPROF_GENCMP) then
-        cp $CPLPROF_GENCMP $BASEGEN_CPLPROFFILE || echo "ERROR in ${0}:  could not copy $CPLPROF_GENCMP to $BASEGEN_CPLPROFFILE " >>& $TESTSTATUS_LOG
-        chmod ug+w,a+r $BASEGEN_CPLPROFFILE
-      endif
+    if ($?CPLPROF_GENCMP) then
+      cp -f $CPLPROF_GENCMP $BASEGEN_CPLPROFFILE || echo "ERROR in ${0}:  could not copy $CPLPROF_GENCMP to $BASEGEN_CPLPROFFILE " >>& $TESTSTATUS_LOG
+      chmod ug+w,a+r $BASEGEN_CPLPROFFILE
     endif
   else
     set genstatus = "BFAIL"
@@ -240,17 +227,14 @@ if ( $MODEL_GEN_COMP != "UNSET" ) then
       foreach extension ( $extension_list )
          set test_hist=`cd $RUNDIR; ls -1 ${CASE}.${MODEL_GEN_COMP}*.${extension}*.nc | tail -1`
          set base_hist="${MODEL_GEN_COMP}.${extension}.nc"
-         set base_name="undefined"
          set ran="nope"
          if ( "$type" == "compare_hist" && $?BASECMP_NAME ) then
             set ran="yep"
-            set base_name=$BASECMP_NAME
             $CASETOOLS/component_compare.sh -baseline_dir $BASECMP_DIR \
              -test_dir $RUNDIR -test_hist "$test_hist" -baseline_hist $base_hist >> $TESTSTATUS_LOG
          endif
          if ( "$type" == "generate" && $?BASEGEN_NAME ) then
             set ran="yep"
-            set base_name=$BASEGEN_NAME
             $CASETOOLS/component_generate.sh -baseline_dir $BASEGEN_DIR \
              -test_dir $RUNDIR -test_hist "$test_hist" -baseline_hist $base_hist >> $TESTSTATUS_LOG
          endif
@@ -258,12 +242,12 @@ if ( $MODEL_GEN_COMP != "UNSET" ) then
             set compstatus = `tail -1 $TESTSTATUS_LOG | cut -d ':' -f 1`
             if ( "$compstatus" != "BFAIL_NA" ) then
                set all_bfail=0
-               echo "$compstatus ${CASEBASEID}.${MODEL_GEN_COMP}.${extension}.${type}.${base_name} " >>& $TESTSTATUS_OUT
+               echo "$compstatus ${CASEBASEID}.${MODEL_GEN_COMP}.${extension}.${type}.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
             endif
          endif
       end
       if ( $all_bfail  == 1 && "$ran" == "yep" ) then
-         echo "BFAIL_NA ${CASEBASEID}.${MODEL_GEN_COMP}.all_extensions.${type}.${base_name} " >>& $TESTSTATUS_OUT
+         echo "BFAIL_NA ${CASEBASEID}.${MODEL_GEN_COMP}.all_extensions.${type}.${BASECMP_NAME} " >>& $TESTSTATUS_OUT
       endif
    end
 endif
@@ -315,7 +299,7 @@ if ( "$memleak" !~ "" || "$pesmaxmem_incr" != "" || "$tput_decr" !~ "" || "$tput
 endif
 
 if ( ${CASE} =~ *_IOP* ) then
-  cat ../${iopbase_case}/TestStatus >> $TESTSTATUS_OUT
+  cat ${iopbase_case}/TestStatus >> $TESTSTATUS_OUT
 endif
 
 #======================================================================
