Reduce number of tests while debugging

diff --git a/.github/workflows/eamxx-kokkos-develop-testing.yml b/.github/workflows/eamxx-kokkos-develop-testing.yml
--- a/.github/workflows/eamxx-kokkos-develop-testing.yml
+++ b/.github/workflows/eamxx-kokkos-develop-testing.yml
@@ -73,7 +73,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        build_type: [sp, dbg, fpe, opt]
+        build_type: [dbg] #[sp, dbg, fpe, opt]
     name: gcc-openmp / ${{ matrix.build_type }}
     steps:
       - name: Check out the repository
@@ -101,87 +101,87 @@ jobs:
           submit: ${{ env.submit }}
           cmake-configs: CMAKE_CXX_STANDARD=20;Kokkos_ENABLE_IMPL_VIEW_LEGACY=ON;Kokkos_ENABLE_DEPRECATED_CODE_4=ON;Kokkos_ENABLE_OPENMP=ON;
           ekat: ${{ env.ekat }}
-  gcc-cuda:
-    if: |
-      ${{
-        github.event_name != 'workflow_dispatch' ||
-        (
-          github.event.inputs.job_to_run == 'gcc-cuda' ||
-          github.event.inputs.job_to_run == 'all'
-        )
-      }}
-    runs-on:  [self-hosted, ghci-snl-cuda, cuda, gcc]
-    strategy:
-      fail-fast: false
-      matrix:
-        test:
-          - build_type: sp
-            SK: OFF
-          - build_type: dbg
-            SK: ON
-          - build_type: opt
-            SK: OFF
-    name: gcc-cuda / ${{ matrix.test.build_type }}
-    steps:
-      - name: Check out the repository
-        uses: actions/checkout@v5
-        with:
-          persist-credentials: false
-          show-progress: false
-          submodules: recursive
-      - name: Fetch most recent kokkos develop
-        run: |
-          cd externals/ekat/extern/kokkos
-          if ! git remote | grep -q upstream; then
-            git remote add upstream https://github.com/kokkos/kokkos.git
-          fi
-          git fetch upstream
-          git checkout upstream/develop
-      - name: Show action trigger
-        uses: ./.github/actions/show-workflow-trigger
-      - name: Get CUDA Arch
-        run: |
-          # Ensure nvidia-smi is available
-          if ! command -v nvidia-smi &> /dev/null; then
-              echo "nvidia-smi could not be found. Please ensure you have Nvidia drivers installed."
-              exit 1
-          fi
+  # gcc-cuda:
+  #   if: |
+  #     ${{
+  #       github.event_name != 'workflow_dispatch' ||
+  #       (
+  #         github.event.inputs.job_to_run == 'gcc-cuda' ||
+  #         github.event.inputs.job_to_run == 'all'
+  #       )
+  #     }}
+  #   runs-on:  [self-hosted, ghci-snl-cuda, cuda, gcc]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       test:
+  #         - build_type: sp
+  #           SK: OFF
+  #         - build_type: dbg
+  #           SK: ON
+  #         - build_type: opt
+  #           SK: OFF
+  #   name: gcc-cuda / ${{ matrix.test.build_type }}
+  #   steps:
+  #     - name: Check out the repository
+  #       uses: actions/checkout@v5
+  #       with:
+  #         persist-credentials: false
+  #         show-progress: false
+  #         submodules: recursive
+  #     - name: Fetch most recent kokkos develop
+  #       run: |
+  #         cd externals/ekat/extern/kokkos
+  #         if ! git remote | grep -q upstream; then
+  #           git remote add upstream https://github.com/kokkos/kokkos.git
+  #         fi
+  #         git fetch upstream
+  #         git checkout upstream/develop
+  #     - name: Show action trigger
+  #       uses: ./.github/actions/show-workflow-trigger
+  #     - name: Get CUDA Arch
+  #       run: |
+  #         # Ensure nvidia-smi is available
+  #         if ! command -v nvidia-smi &> /dev/null; then
+  #             echo "nvidia-smi could not be found. Please ensure you have Nvidia drivers installed."
+  #             exit 1
+  #         fi
 
-          # Get the GPU model from nvidia-smi, and set env for next step
-          gpu_model=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
-          case "$gpu_model" in
-              *"H100"*)
-                  echo "Hopper=ON" >> $GITHUB_ENV
-                  echo "CUDA_ARCH=90" >> $GITHUB_ENV
-                  ARCH=90
-                  ;;
-              *"A100"*)
-                  echo "Ampere=ON" >> $GITHUB_ENV
-                  echo "CUDA_ARCH=80" >> $GITHUB_ENV
-                  ;;
-              *"V100"*)
-                  echo "Volta=ON" >> $GITHUB_ENV
-                  echo "CUDA_ARCH=70" >> $GITHUB_ENV
-                  ;;
-              *)
-                  echo "Unsupported GPU model: $gpu_model"
-                  exit 1
-                  ;;
-          esac
-      - name: Run tests
-        uses: ./.github/actions/test-all-eamxx
-        with:
-          build_type: ${{ matrix.test.build_type }}
-          machine: ghci-snl-cuda
-          generate: ${{ env.generate }}
-          submit: ${{ env.submit }}
-          cmake-configs: |
-            CMAKE_CXX_STANDARD=20;
-            Kokkos_ENABLE_IMPL_VIEW_LEGACY=ON; # Currently a bug exists in Kokkos' mdspan view impl
-            Kokkos_ENABLE_DEPRECATED_CODE_4=ON; # Remove once PRs merged in MAM4xx and EKAT fixing deprecated code
-            Kokkos_ARCH_HOPPER90=${{ env.Hopper }};
-            Kokkos_ARCH_AMPERE80=${{ env.Ampere }};
-            Kokkos_ARCH_VOLTA70=${{ env.Volta }};
-            CMAKE_CUDA_ARCHITECTURES=${{ env.CUDA_ARCH }};
-            SCREAM_SMALL_KERNELS=${{ matrix.test.SK }};
-          ekat: ${{ env.ekat }}
+  #         # Get the GPU model from nvidia-smi, and set env for next step
+  #         gpu_model=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -n 1)
+  #         case "$gpu_model" in
+  #             *"H100"*)
+  #                 echo "Hopper=ON" >> $GITHUB_ENV
+  #                 echo "CUDA_ARCH=90" >> $GITHUB_ENV
+  #                 ARCH=90
+  #                 ;;
+  #             *"A100"*)
+  #                 echo "Ampere=ON" >> $GITHUB_ENV
+  #                 echo "CUDA_ARCH=80" >> $GITHUB_ENV
+  #                 ;;
+  #             *"V100"*)
+  #                 echo "Volta=ON" >> $GITHUB_ENV
+  #                 echo "CUDA_ARCH=70" >> $GITHUB_ENV
+  #                 ;;
+  #             *)
+  #                 echo "Unsupported GPU model: $gpu_model"
+  #                 exit 1
+  #                 ;;
+  #         esac
+  #     - name: Run tests
+  #       uses: ./.github/actions/test-all-eamxx
+  #       with:
+  #         build_type: ${{ matrix.test.build_type }}
+  #         machine: ghci-snl-cuda
+  #         generate: ${{ env.generate }}
+  #         submit: ${{ env.submit }}
+  #         cmake-configs: |
+  #           CMAKE_CXX_STANDARD=20;
+  #           Kokkos_ENABLE_IMPL_VIEW_LEGACY=ON; # Currently a bug exists in Kokkos' mdspan view impl
+  #           Kokkos_ENABLE_DEPRECATED_CODE_4=ON; # Remove once PRs merged in MAM4xx and EKAT fixing deprecated code
+  #           Kokkos_ARCH_HOPPER90=${{ env.Hopper }};
+  #           Kokkos_ARCH_AMPERE80=${{ env.Ampere }};
+  #           Kokkos_ARCH_VOLTA70=${{ env.Volta }};
+  #           CMAKE_CUDA_ARCHITECTURES=${{ env.CUDA_ARCH }};
+  #           SCREAM_SMALL_KERNELS=${{ matrix.test.SK }};
+  #         ekat: ${{ env.ekat }}
